var list = {
    animals: [
        {
            title: "Vaquite",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=2e383dcd-2f82-4a7a-bd56-a9878d2d31d7",
            left: 10,
            longlat: [26.73, -110.71],
            foundin: ["Northern part of Gulf of Mexico"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Asian Elephants",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=fa049e65-c187-46e8-b7cd-af8fb34e0b23",
            left: 50000,
            longlat: [8.03, 80.82],
            foundin: [
                "Minneriya National Park Sri Lanka",
                "Nagarhole Reserves Karnataka,India",
                "Sumatra,Indonesia",
            ],
            info: "- Asian elephants can tear down trees or pick up a blade of grass with their trunks.- https://en.wikipedia.org/wiki/Asian_elephant",
        },
        {
            title: "Snow Leopard",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=0746691a-53f6-4ec1-98ae-312e7aed5d1b",
            left: 6590,
            longlat: [43.66, 101.52],
            foundin: [
                "Gobi Gurvansaikhan National Park,Mongolia",
                " Jigme Dorji National Park,Bhutan",
                "Shey-Phoksundo National Park, Nepal",
                "Hemis National Park.India",
            ],
            info: "- They can nearly cover the distance of a marathon in one night.- https://en.wikipedia.org/wiki/Snow_leopard",
        },
        {
            title: "Gorilla",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=6049fdd6-3102-4a52-8777-86067a7016b8",
            left: 1063,
            longlat: [-1.4, 29.56],
            foundin: [
                "Volcanoes National Park,Rwanda",
                "Mgahinga National Park,Uganda",
                "Virunga National Park,Congo",
                " Bwindi Impenetrable National Park,Uganda",
            ],
            info: "- Some gorillas in captivity have learned to use sign language to communicate with humans.- https://en.wikipedia.org/wiki/Gorilla",
        },
        {
            title: "Javan Rhinoceros",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=ff3d7415-26af-46af-b39d-f7e29f2ac3eb",
            left: 68,
            longlat: [-6.78, 105.37],
            foundin: ["Ujung Kulon National Park,Indonesia"],
            info: "- They're solitary animals, except for mating pairs and mothers with young.- https://en.wikipedia.org/wiki/Javan_rhinoceros",
        },
        {
            title: "Irrawaddy Dolphins",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=bc16cc8b-30a3-4145-b7b6-ae90f7e41dc3",
            left: 100,
            longlat: [15.51, 95.14],
            foundin: ["Ayeyarwady River, Myanmar", "Mahakam River, Indonesian"],
            info: "- They are often seen spyhopping and observing the environment around them.- https://en.wikipedia.org/wiki/Irrawaddy_dolphin",
        },
        {
            title: "Giant Panda",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=44339327-8318-45ce-936d-de0bbf509cf2",
            left: 1864,
            longlat: [29, 106],
            foundin: ["South-West, China"],
            info: "- They occasionally eat something other than bamboo.- https://en.wikipedia.org/wiki/Giant_panda",
        },
        {
            title: "Tiger",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=6133c975-db57-49ff-b4e4-169bda8f1b75",
            left: 3900,
            longlat: [23.41, 80.57],
            foundin: [
                "Bandhavgarh National Park,India",
                "Ranthambore National Park,Rajasthan",
                "Sundarbans and the Chittagong Hill, Bangladesh",
                "South China",
                "Sumatra",
                "Siberia",
                "Nepal",
            ],
            info: "- Tigers love to swim and play in the water.- https://en.wikipedia.org/wiki/Tiger",
        },
        {
            title: "Whooping Crane",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=d775d512-f54b-4951-9b63-48f430120080",
            left: 505,
            longlat: [39.32, -111.09],
            foundin: ["North-America", "Central Mexico", "Utah"],
            info: "-  Adult Whooping Cranes are identified by a red skin patch on their forehead, black “mustache” and legs, and black wing tips visible in flight.- https://en.wikipedia.org/wiki/Whooping_crane",
        },
        // {
        //   title: "Tasmanian Devil",
        //   link: "https://go.echoar.xyz/w8P3",
        //   left: 10000,
        //   longlat:[36.6, -121.89],
        //   foundin: ["Tasmania"],
        // },
        {
            title: "Blue Whale",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=0d99c0a5-6f22-48b6-b159-bd936abb7673",
            left: 24000,
            longlat: [36.6, -121.89],
            foundin: [
                "Gulf of St. Lawrence",
                "Coast of Monterey",
                "baja California,Mexico",
            ],
            info: "- Blue whales are the largest animals ever known to have lived on Earth.- https://en.wikipedia.org/wiki/Blue_whale",
        },
    ],

};
