var list = {
    animals: [
        {
            title: "Vaquite",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=e16a8d7a-7f4d-4fb8-84ba-925eb9f92cc2",
            left: 10,
            longlat: [26.73, -110.71],
            foundin: ["Northern part of Gulf of Mexico"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Asian Elephants",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=fa049e65-c187-46e8-b7cd-af8fb34e0b23",
            left: 50000,
            longlat: [8.03, 80.82],
            foundin: [
                "Minneriya National Park Sri Lanka",
                "Nagarhole Reserves Karnataka,India",
                "Sumatra,Indonesia",
            ],
            info: "- Asian elephants can tear down trees or pick up a blade of grass with their trunks.- https://en.wikipedia.org/wiki/Asian_elephant",
        },
        {
            title: "Snow Leopard",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=0f9ead74-5bc3-4d34-a95d-dcb576128a94",
            left: 6590,
            longlat: [43.66, 101.52],
            foundin: [
                "Gobi Gurvansaikhan National Park,Mongolia",
                " Jigme Dorji National Park,Bhutan",
                "Shey-Phoksundo National Park, Nepal",
                "Hemis National Park.India",
            ],
            info: "- They can nearly cover the distance of a marathon in one night.- https://en.wikipedia.org/wiki/Snow_leopard",
        },
        {
            title: "Gorilla",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=3adbe5fb-871d-43d2-a514-bf8df391beb7",
            left: 1063,
            longlat: [-1.4, 29.56],
            foundin: [
                "Volcanoes National Park,Rwanda",
                "Mgahinga National Park,Uganda",
                "Virunga National Park,Congo",
                " Bwindi Impenetrable National Park,Uganda",
            ],
            info: "- Some gorillas in captivity have learned to use sign language to communicate with humans.- https://en.wikipedia.org/wiki/Gorilla",
        },
        {
            title: "Javan Rhinoceros",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=a402342b-0fe2-4c1f-abd5-4109a3c00f7a",
            left: 68,
            longlat: [-6.78, 105.37],
            foundin: ["Ujung Kulon National Park,Indonesia"],
            info: "- They're solitary animals, except for mating pairs and mothers with young.- https://en.wikipedia.org/wiki/Javan_rhinoceros",
        },
        {
            title: "Irrawaddy Dolphins",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=52d52228-4de7-4260-8306-c87a262b234b",
            left: 100,
            longlat: [15.51, 95.14],
            foundin: ["Ayeyarwady River, Myanmar", "Mahakam River, Indonesian"],
            info: "- They are often seen spyhopping and observing the environment around them.- https://en.wikipedia.org/wiki/Irrawaddy_dolphin",
        },
        {
            title: "Giant Panda",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=60c68fd7-bcd8-40ca-8005-99b82021c9b1",
            left: 1864,
            longlat: [29, 106],
            foundin: ["South-West, China"],
            info: "- They occasionally eat something other than bamboo.- https://en.wikipedia.org/wiki/Giant_panda",
        },
        {
            title: "Tiger",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=b28a4f8d-599f-4d4d-b22b-bba62c3e45e1",
            left: 3900,
            longlat: [23.41, 80.57],
            foundin: [
                "Bandhavgarh National Park,India",
                "Ranthambore National Park,Rajasthan",
                "Sundarbans and the Chittagong Hill, Bangladesh",
                "South China",
                "Sumatra",
                "Siberia",
                "Nepal",
            ],
            info: "- Tigers love to swim and play in the water.- https://en.wikipedia.org/wiki/Tiger",
        },
        {
            title: "Whooping Crane",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=3370f0d9-943f-408a-a9ef-3d0481090b5e",
            left: 505,
            longlat: [39.32, -111.09],
            foundin: ["North-America", "Central Mexico", "Utah"],
            info: "-  Adult Whooping Cranes are identified by a red skin patch on their forehead, black “mustache” and legs, and black wing tips visible in flight.- https://en.wikipedia.org/wiki/Whooping_crane",
        },
        // {
        //   title: "Tasmanian Devil",
        //   link: "https://go.echoar.xyz/w8P3",
        //   left: 10000,
        //   longlat:[36.6, -121.89],
        //   foundin: ["Tasmania"],
        // },
        {
            title: "Blue Whale",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=f2cd0994-f758-45c0-961b-2eefd164413f",
            left: 24000,
            longlat: [36.6, -121.89],
            foundin: [
                "Gulf of St. Lawrence",
                "Coast of Monterey",
                "baja California,Mexico",
            ],
            info: "- Blue whales are the largest animals ever known to have lived on Earth.- https://en.wikipedia.org/wiki/Blue_whale",
        },
    ],

};
