var list = {
    animals: [
        {
            title: "Camel",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=0428c5b6-477f-4936-a236-9e4bea8081d4",
            left: 10,
            longlat: [23.4162, 25.6628],
            foundin: ["Famously Found in Africa"],
            info: "- A camel is an even-toed ungulate in the genus Camelus that bears distinctive fatty deposits known as humps on its back. Camels have long been domesticated and, as livestock, they provide food and textiles.- https://en.wikipedia.org/wiki/Camel",
        },
        {
            title: "Elephant",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=fa049e65-c187-46e8-b7cd-af8fb34e0b23",
            left: 10,
            longlat: [-5.9175, 12.5484],
            foundin: ["Famously Found in Rainforest of Africa"],
            info: "- Elephants are the largest existing land animals. Three species are currently recognised: the African bush elephant, the African forest elephant, and the Asian elephant. Elephantidae is the only surviving family of the order Proboscidea; extinct members include the mastodons.- https://en.wikipedia.org/wiki/Elephant",
        },
        {
            title: "Cobra ",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=ea00563f-a58b-4d82-a4c9-1311bc496469",
            left: 10,
            longlat: [12.2602, 77.1461],
            foundin: ["Famously Found in South Asia and Deserts of Africa"],
            info: "- Cobra, any of various species of highly venomous snakes, most of which expand the neck ribs to form a hood. While the hood is characteristic of cobras, not all of them are closely related. Cobras are found from southern Africa through southern Asia to islands of Southeast Asia..- https://en.wikipedia.org/wiki/King_cobra",
        },
        {
            title: "Panda",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=44339327-8318-45ce-936d-de0bbf509cf2",
            left: 10,
            longlat: [30.5961, 114.2977],
            foundin: ["Famously Found in Central parts of China"],
            info: "- The giant panda, also known as the panda bear or simply the panda, is a bear native to South Central China. It is characterised by its bold black-and-white coat and rotund body. The name giant panda is sometimes used to distinguish it from the red panda, a neighboring musteloid.- https://en.wikipedia.org/wiki/Giant_panda",
        },
        {
            title: "Tiger",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=6133c975-db57-49ff-b4e4-169bda8f1b75",
            left: 10,
            longlat: [25.0376, 76.4563],
            foundin: ["Famously Found in South Asia"],
            info: "- The tiger is the largest living cat species and a member of the genus Panthera. It is most recognisable for its dark vertical stripes on orange-brown fur with a lighter underside. It is an apex predator, primarily preying on ungulates such as deer and wild boar.- https://en.wikipedia.org/wiki/Tiger",
        },
        {
            title: "Kangaroo",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=3e84ba93-93d3-4478-9a01-b4983ac6843b",
            left: 10,
            longlat: [-25.2744, 133.7751],
            foundin: ["Famously Found in Australia"],
            info: "- The kangaroo is a marsupial from the family Macropodidae. In common use the term is used to describe the largest species from this family, the red kangaroo, as well as the antilopine kangaroo, eastern grey kangaroo, and western grey kangaroo. Kangaroos are indigenous to Australia and New Guinea..- https://en.wikipedia.org/wiki/Kangaroo",
        },
        {
            title: "Deer",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=50f04a3a-2e07-4eea-846e-807fdb75a98d",
            left: 10,
            longlat: [54.5260, -105.2551],
            foundin: ["Famously Found in Europe, North and South America"],
            info: "- Deer or true deer are hoofed ruminant mammals forming the family Cervidae. The two main groups of deer are the Cervinae, including the muntjac, the elk, the red deer, the fallow deer, and the chital; and the Capreolinae, including the reindeer, the roe deer, the mule deer, and the moose.- https://en.wikipedia.org/wiki/Deer",
        },
        {
            title: "Stork ",
            link: "https://console.echoar.xyz/webar?key=dawn-band-5336&entry=d775d512-f54b-4951-9b63-48f430120080",
            left: 10,
            longlat: [40.4637, -3.7492],
            foundin: ["Famously Found in North and South Europe"],
            info: "- Storks are large, long-legged, long-necked wading birds with long, stout bills. They belong to the family called Ciconiidae, and make up the order Ciconiiformes. Ciconiiformes previously included a number of other families, such as herons and ibises, but those families have been moved to other orders..- https://en.wikipedia.org/wiki/Stork",
        },
        {
            title: "Racoon",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=ed8434d0-013e-4522-8759-3226c387a1a8",
            left: 10,
            longlat: [37.0902, -95.7129],
            foundin: ["Famously Found in North and South Europe"],
            info: "- The raccoon, sometimes called the common raccoon to distinguish it from other species, is a medium-sized mammal native to North America. It is the largest of the procyonid family, having a body length of 40 to 70 cm, and a body weight of 5 to 26 kg.- https://en.wikipedia.org/wiki/Raccoon",
        },
        {
            title: "Monkey",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=eb34f15f-e036-4cba-b3ba-5cdbc3809d3d",
            left: 10,
            longlat: [-8.7832, -55.4915],
            foundin: ["Famously Found in North and South Europe"],
            info: "- Monkey is a common name that may refer to certain groups or species of simian mammals of infraorder Simiiformes. The term is applied descriptively to groups of primates, such as families of New World monkeys and Old World monkeys..- https://en.wikipedia.org/wiki/Monkey",
        },
        {
            title: "Polar bear",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=1b20a355-67ea-4d0c-9d3d-394028a20fd2",
            left: 10,
            longlat: [71.7069, -42.6043],
            foundin: ["Famously Found in Polar Regions"],
            info: "- The polar bear is a hypercarnivorous bear whose native range lies largely within the Arctic Circle, encompassing the Arctic Ocean, its surrounding seas and surrounding land masses. It is the largest extant bear species, as well as the largest extant land carnivore .- https://en.wikipedia.org/wiki/Polar_bear",
        },
        {
            title: "Narwhal ",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=56a7d834-dd57-4cd4-a81d-991e739d42e1",
            left: 10,
            longlat: [48.6987, -72.3586],
            foundin: ["Famously Found in Polar Regions"],
            info: "- The narwhal or narwhale is a medium-sized toothed whale that possesses a large tusk from a protruding canine tooth. It lives year-round in the Arctic waters around Greenland, Canada, and Russia. It is one of two living species of whale in the family Monodontidae, along with the beluga whale..- https://en.wikipedia.org/wiki/Narwhal",
        },
    ],

};