var list = {
    animals: [
        {
            title: "Camel",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=0428c5b6-477f-4936-a236-9e4bea8081d4",
            left: 10,
            longlat: [23.4162, 25.6628],
            foundin: ["Famously Found in Africa"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Elephant",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=fa049e65-c187-46e8-b7cd-af8fb34e0b23",
            left: 10,
            longlat: [-5.9175, 12.5484],
            foundin: ["Famously Found in Rainforest of Africa"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Cobra ",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=ea00563f-a58b-4d82-a4c9-1311bc496469",
            left: 10,
            longlat: [12.2602, 77.1461],
            foundin: ["Famously Found in South Asia and Deserts of Africa"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Panda",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=60c68fd7-bcd8-40ca-8005-99b82021c9b1",
            left: 10,
            longlat: [30.5961, 114.2977],
            foundin: ["Famously Found in Central parts of China"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Tiger",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=b28a4f8d-599f-4d4d-b22b-bba62c3e45e1",
            left: 10,
            longlat: [25.0376, 76.4563],
            foundin: ["Famously Found in South Asia"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Kangaroo",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=3e84ba93-93d3-4478-9a01-b4983ac6843b",
            left: 10,
            longlat: [-25.2744, 133.7751],
            foundin: ["Famously Found in Australia"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Deer",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=50f04a3a-2e07-4eea-846e-807fdb75a98d",
            left: 10,
            longlat: [54.5260, -105.2551],
            foundin: ["Famously Found in Europe, North and South America"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Stork ",
            link: "https://console.echoar.xyz/webar?key=fragrant-mountain-7260&entry=3370f0d9-943f-408a-a9ef-3d0481090b5e",
            left: 10,
            longlat: [40.4637, -3.7492],
            foundin: ["Famously Found in North and South Europe"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Racoon",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=ed8434d0-013e-4522-8759-3226c387a1a8",
            left: 10,
            longlat: [37.0902, -95.7129],
            foundin: ["Famously Found in North and South Europe"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Monkey",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=eb34f15f-e036-4cba-b3ba-5cdbc3809d3d",
            left: 10,
            longlat: [-8.7832, -55.4915],
            foundin: ["Famously Found in North and South Europe"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Polar bear",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=1b20a355-67ea-4d0c-9d3d-394028a20fd2",
            left: 10,
            longlat: [71.7069, -42.6043],
            foundin: ["Famously Found in Polar Regions"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
        {
            title: "Narwhal ",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=56a7d834-dd57-4cd4-a81d-991e739d42e1",
            left: 10,
            longlat: [48.6987, -72.3586],
            foundin: ["Famously Found in Polar Regions"],
            info: "- They have unique facial markings with a black ring around each eye and curved, black lips that make them look as if they are smiling.- https://en.wikipedia.org/wiki/Vaquita",
        },
    ],

};
