var list = {
    animals: [
        {
            title: "Eiffel Tower",
            link: "https://console.echoar.xyz/webar?key=noisy-bar-1396&entry=1bbbec3d-f398-45b8-a353-e46b566f5d90",
            left: 10,
            longlat: [48.85, 2.29],
            foundin: ["Paris, France"],
            info: "- The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower. - https://en.wikipedia.org/wiki/Eiffel_Tower",
        },
        {
            title: "Taj Mahal",
            link: "https://console.echoar.xyz/webar?key=cool-wind-0510&entry=41276508-fef2-41c4-b298-07bc678cef07",
            left: 50000,
            longlat: [27.17, 78.04],
            foundin: ["Agra, India"],
            info: "The Taj Mahal is an ivory-white marble mausoleum on the southern bank of the river Yamuna in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself.- https://en.wikipedia.org/wiki/Asian_elephant",
        },
        {
            title: "Statue of Liberty",
            link: "https://console.echoar.xyz/webar?key=bitter-union-6709&entry=b641a318-7d3c-4565-b81e-d4fd5a570e1c",
            left: 6590,
            longlat: [40.68, -74.04],
            foundin: [
                "Gobi Gurvansaikhan National Park,Mongolia",
                " Jigme Dorji National Park,Bhutan",
                "Shey-Phoksundo National Park, Nepal",
                "Hemis National Park.India",
            ],
            info: "- They can nearly cover the distance of a marathon in one night.- https://en.wikipedia.org/wiki/Snow_leopard",
        },
        {
            title: "Machu Picchu",
            link: "https://console.echoar.xyz/webar?key=cool-wind-0510&entry=b20babe4-d267-47bc-9379-5ae480daa596",
            left: 1063,
            longlat: [-13.16, -72.54],
            foundin: [
                "Volcanoes National Park,Rwanda",
                "Mgahinga National Park,Uganda",
                "Virunga National Park,Congo",
                " Bwindi Impenetrable National Park,Uganda",
            ],
            info: "- Some gorillas in captivity have learned to use sign language to communicate with humans.- https://en.wikipedia.org/wiki/Gorilla",
        },
        {
            title: "Colosseum",
            link: "https://console.echoar.xyz/webar?key=fancy-dust-5994&entry=8e22bf5f-dfb2-49b3-b022-38379e751d32",
            left: 68,
            longlat: [41.89, 12.09],
            foundin: ["Ujung Kulon National Park,Indonesia"],
            info: "- They're solitary animals, except for mating pairs and mothers with young.- https://en.wikipedia.org/wiki/Javan_rhinoceros",
        },
        {
            title: "Petra, Jordan",
            link: "https://console.echoar.xyz/webar?key=fancy-dust-5994&entry=af3db530-f012-4a34-9bc1-3fd99f221b70",
            left: 100,
            longlat: [30.32, 35.44],
            foundin: ["Ayeyarwady River, Myanmar", "Mahakam River, Indonesian"],
            info: "- They are often seen spyhopping and observing the environment around them.- https://en.wikipedia.org/wiki/Irrawaddy_dolphin",
        },
        {
            title: "Golden Gate Bridge",
            link: "https://console.echoar.xyz/webar?key=cool-wind-0510&entry=71dc00f7-93fe-4c8b-b378-d7e2866ad63b",
            left: 1864,
            longlat: [37.81, -122.47],
            foundin: ["South-West, China"],
            info: "- They occasionally eat something other than bamboo.- https://en.wikipedia.org/wiki/Giant_panda",
        },
        {
            title: "Great Wall of China",
            link: "https://console.echoar.xyz/webar?key=cool-wind-0510&entry=b2e185bd-3897-4b1f-804e-1b300817ca57",
            left: 3900,
            longlat: [40.43, 116.57],
            foundin: [
                "Bandhavgarh National Park,India",
                "Ranthambore National Park,Rajasthan",
                "Sundarbans and the Chittagong Hill, Bangladesh",
                "South China",
                "Sumatra",
                "Siberia",
                "Nepal",
            ],
            info: "- Tigers love to swim and play in the water.- https://en.wikipedia.org/wiki/Tiger",
        },
        {
            title: "Uluru",
            link: "https://console.echoar.xyz/webar?key=cool-wind-0510&entry=880be458-b1a0-4ba2-99c2-93d5e18b7131",
            left: 505,
            longlat: [-25.34, 131.03],
            foundin: ["North-America", "Central Mexico", "Utah"],
            info: "-  Adult Whooping Cranes are identified by a red skin patch on their forehead, black “mustache” and legs, and black wing tips visible in flight.- https://en.wikipedia.org/wiki/Whooping_crane",
        },
        // {
        //   title: "Tasmanian Devil",
        //   link: "https://go.echoar.xyz/w8P3",
        //   left: 10000,
        //   longlat:[36.6, -121.89],
        //   foundin: ["Tasmania"],
        // },
        {
            title: "Christ the Redeemer",
            link: "https://console.echoar.xyz/webar?key=cool-wind-0510&entry=9be08598-8a24-4e22-a80a-422a11bb698b",
            left: 24000,
            longlat: [-22.95, -43.21],
            foundin: [
                "Gulf of St. Lawrence",
                "Coast of Monterey",
                "baja California,Mexico",
            ],
            info: "- Blue whales are the largest animals ever known to have lived on Earth.- https://en.wikipedia.org/wiki/Blue_whale",
        },
        {
            title: "Sydney Opera House",
            link: "https://console.echoar.xyz/webar?key=cool-wind-0510&entry=d94c7310-3cec-40f9-8919-86424dde93a0",
            left: 2400,
            longlat: [-33.85, 151.21],
            foundin: [
                "Gulf of St. Lawrence",
                "Coast of Monterey",
                "baja California,Mexico",
            ],
            info: "- Blue whales are the largest animals ever known to have lived on Earth.- https://en.wikipedia.org/wiki/Blue_whale",
        },
        {
            title: "Spasskaya Bashnya, Moscow",
            link: "https://console.echoar.xyz/webar?key=cool-wind-0510&entry=e15040ff-9c6c-4d73-8f60-276f8a48f86f",
            left: 2400,
            longlat: [55.75, 37.62],
            foundin: [
                "Gulf of St. Lawrence",
                "Coast of Monterey",
                "baja California,Mexico",
            ],
            info: "- Blue whales are the largest animals ever known to have lived on Earth.- https://en.wikipedia.org/wiki/Blue_whale",
        },
    ],

};
